### ISSUE TITLE
Where to find the JAR?

### ISSUE THREAD

**Issue by Vadorequest** [chubbard/WatchTask#5]
Hello,

is the JAR available somewhere?

Thanks.

**Comment by chubbard** [comment]
Right now no.  You have to build it from the source using the maven project.  I'll work on getting a compiled version up hosted somewhere.

**Comment by Vadorequest** [comment]
I couldn't find out how to compile it, I'm not exactly an expert in Java. Tried from Eclipse->export->JAR but didn't work out.

**Comment by chubbard** [comment]
The easiest way is to run 

mvn clean install

Then inside the target directory it'll produce watch-task-1.0-SNAPSHOT.jar

**Comment by eiselems** [comment]
@Vadorequest as chubbard told you, you will need maven.

You can get it at https://maven.apache.org/. After you installed it and added it to your PATH. You can run
´mvn clean install´ from your project folder and fetch the generated jar from /target

**Comment by lopezdonaque** [comment]
Hi,  could you add the jar file into a dist folder?

**Comment by chubbard** [comment]
Ok I just put the instructions on the readme and hosted it on jitter.io.  Follow the link to the instructions and you can add it as a dependency.  Thank you for your patience.

**Comment by lopezdonaque** [comment]
Hi, my project is not using Maven so if someone needs to download it here some instructions:

Download Maven binary (apache-maven-3.5.0-bin.zip):

> https://maven.apache.org/download.cgi


Run:

> apache-maven-3.5.0\bin\mvn.cmd dependency:get -DremoteRepositories=https://jitpack.io -Dartifact=com.github.chubbard:WatchTask:-SNAPSHOT -Ddest=.


Thanks

**Comment by chubbard** [comment]
Thanks I'll add those instructions to the README.
